### ISSUE TITLE
error: cannot use import statement outside a module?

### ISSUE THREAD

**Issue by benkoshy** [mitschabaude/esbuild-plugin-wat#2]
I'm getting an annoying error. Am I doing something obviously wrong? Any pointers would be much appreciated.

```sh
$ node ./esbuild.config.js --watch
(node:3948) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/koshy/Documents/www/BensRails/mto/esbuild.config.js:3
import watPlugin from 'esbuild-plugin-wat';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
```

```js
// esbuild.config.js
const path = require('path')
const esbuild = require('esbuild')
import watPlugin from 'esbuild-plugin-wat';

esbuild.build({
  entryPoints: ['./application.js'],
  bundle: true,
  outdir: path.join(process.cwd(), "app/assets/builds"),
  absWorkingDir: path.join(process.cwd(), "app/javascript"),
  watch: process.argv.includes("--watch"),
  sourcemap: true,
  mainFields: ['module', 'main'],
  plugins: [
    watPlugin() // options are documented below
  ],
}).catch(e => (console.error(e), process.exit(1)))
```

My package.json
```json
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "3.0.1",
    "@hotwired/turbo-rails": "7.1.1",
    "@tailwindcss/forms": "0.5.1",
    "autoprefixer": "10.4.5",
    "esbuild": "0.14.38",
    "esbuild-plugin-wat": "0.2.7",
    "postcss": "8.4.12",
    "tailwindcss": "3.0.24",
    "tailwindcss-stimulus-components": "3.0.4",
    "three": "0.141.0",
    "web-ifc-three": "0.0.117"
  },
  "scripts": {
    "build": "node ./esbuild.config.js",
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify"
  }
}
```

**Comment by mitschabaude** [comment]
first pointer: try to google errors before you open an issue. this is an extremely well-known and well-documented issue. https://www.google.com/search?channel=fs&client=ubuntu&q=cannot+use+import+statement+outside+a+module+node

second pointer: look at the error message before opening an issue:
> Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

third pointer: set "type: module" in the package.json, or rename files that have an `import` statement to have an `.mjs` extension

EDIT: sorry if this came across unfriendly. I wish you all the best on your journey! :D

**Comment by benkoshy** [comment]
Hey I appreciate your msg, apologies for the question, and the maintenance burdens etc. I agree to your suggestions, however the following might be of benefit (in my case, a tyro esbuild user):

I had followed the readme to a T, I was expecting smooth sailing.

But, unfortunately, the error msg was not particularly clear (to me): I thought I had already taken care of the module issue by following the esbuild docs with the type module included. I wasn't sure what to change to `.mjs`. The initial searching was not particularly fruitful - and granted: yes, all questions can be answered by diligent study and Googling, but I thought the answer might be extremely obvious to someone who knows, vs someone who doesn't. I didn't see many issues open, and thought: it's worth a shot. 

Still, is it worth a documentation PR?

**Comment by mitschabaude** [comment]
Hey @benkoshy, thanks for your reply! Gotcha, yeah the JS module schism is hella confusing if you're new. Not sure if it's worth the doc PR but I'd merge it for sure
